openeuropa/oe_authentication

composer.json

Upgrade minimum stability of drupal core to use alpha versions whenever they are ready and avoid using dev versions.
- Changed: Add alpha minimum stability to drupal core

OPENEUROPA-632: Add minimum stability to drupal core.

---

src/UserProvider.php

The problem here is that the CAS response from ECAS does not contain the user email in the assumed `cas:email` key of the XML. The `demo-server` of the PCas library does. 
This PR fixes the error by looking for the user based on the user name found in the `cas:user` key which is part of a standard [CAS response](https://apereo.github.io/cas/5.1.x/protocol/CAS-Protocol-Specification.html#252-response) for ticket validation.
In a follow up we need to ensure that retrieving the email is done for both ECAS and the demo-server.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-164: Authentication: fix login error on ECAS redirect

---

oe_authentication.module
oe_authentication.services.yml
src/Authentication/Provider/Authentication.php
src/Controller/AuthenticationController.php
src/Exception/AuthenticationException.php
src/Routing/RouteSubscriber.php
src/UserProvider.php
tests/Kernel/PCasFactoryTest.php

Consolidate the oe_authentication Drupal module and its integration with ECAS.
UPDATE: As agreed, we will merge what we had and continue on two other tracks while what we have so far stays in 0.x:
* 1.x - Using the Drupal CAS module
* 2.x - Abstracting the authentication layer to use other authentication systems as well.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1177: Consolidate oe_authentication

---

README.md
config/install/oe_authentication.settings.yml
oe_authentication.install
runner.yml.dist
src/Event/EuLoginEventSubscriber.php
src/OeAuthenticationServiceProvider.php
src/Service/EuLoginValidator.php

Change settings for CAS and module to have production values by default.
Set development values in task-runner file.
- Changed: settings for CAS and module
- Added: Task and config values processing

OPENEUROPA-1209: Change settings for CAS and module

---

config/install/oe_authentication.settings.yml

Fixed.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1227: EULogin validation service path is wrong

---

.drone.yml
README.md
composer.json

Components dependencies:
- Update some version to use tilde, so it uses the minimal minor version and also for a consistency use decimal number as the version.
- Update some packages to use minimal minor version.
- Added composer boundary to test lowest and highest.
- Added packagist badge.

OPENEUROPA-784: Make sure component dependencies are as relaxed as possible.

---

oe_authentication.install

Because we no longer use the patch from https://www.drupal.org/project/cas/issues/2996955 we need to fall back to a default email address (temporary).
- Added:
- Changed: Email handling method.
- Deprecated:
- Removed:
- Fixed:
- Security:

OPENEUROPA-1197: Add missing configuration for emails.

---

composer.json
oe_authentication.install
runner.yml.dist
tests/features/login.feature
tests/features/logout.feature

Currently, if logged in with the Pcas Demo server using the oe_authentication component, the logout action fails as no redirect URL can be built to redirect back to (see attachment)
Fix this so that login in with the demo server works. If needed, PR should be opened also on pcas demo.

OPENEUROPA-1260: Fix authentication logout redirect for the demo server.

---

runner.yml.dist

#31: Avoid changing default.settings.php
- Changed: Change runner.yml.dist to first run the `drupal:settings-setup` and only after append code, to `settings.override.php`

OPENEUROPA-627: Avoid touching default.settings.php #31.

---

behat.yml.dist
composer.json
oe_authentication.links.menu.yml
oe_authentication.permissions.yml
oe_authentication.routing.yml
runner.yml.dist
src/Form/AuthenticationSettingsForm.php
tests/Behat/AuthenticationContext.php
tests/features/configure_authentication.feature
tests/features/drupal-login.feature
tests/features/ecas-login.feature

Provide the Authentication module with a UI so that users with appropriate permissions can edit and change module configuration.

OPENEUROPA-1501: Implement configuration UI for Authentication.

---

composer.json
oe_authentication.module
oe_authentication.permissions.yml
src/Routing/RouteSubscriber.php
tests/Behat/AuthenticationContext.php
tests/features/user-management.feature

A user that is deleted on the site will be recreated as soon as he logs in again using EU Login. The scope of this issue is to disable the ability to delete a user, even for user 1.
- Removed: Access to user delete

OPENEUROPA-1486: Remove access to user delete.

---

behat.yml.dist
tests/features/ecas-register.feature

In our Behat scenarios we often have:
```
   Scenario: Create Webtools Analytics settings
Given I am logged in as a user with the "administer webtools analytics" permission
And I am on "admin/config/system/oe_webtools_analytics"
```
The step "And I am on "admin/config/system/oe_webtools_analytics"" is clearly not something that business can understand.
We have created a [transformation context|https://github.com/openeuropa/behat-transformation-context] to tackle these kind of situations.
The scope of this issue is to review Behat tests on all our components and turn steps like the one above into business-friendly ones by using the transformation context.

OPENEUROPA-1522: Make sure we don't use Drupal paths in Behat scenarios.

---

composer.json
oe_authentication.install
tests/features/ecas-login.feature

Add redirection to home page if login fails.
- Added: Add redirection to home page if login fails.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1649: Add redirection on login error.

---

behat.yml.dist
tests/Behat/AuthenticationContext.php
tests/Behat/CleanupContext.php
tests/features/ecas-login.feature
tests/features/ecas-register.feature

Currently we are able to have green behat tests only at first time. On other we are getting failed scenarios. It is related to fact that we are creating/blocking users and didn't remove/unblock after scenario.
+ Aligning with ticket OPENEUROPA-1840
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1713: Adjust/correct behat tests of component.

---

oe_authentication.module
src/Routing/RouteSubscriber.php

Replace CAS references with EU Login.
- Added:
- Changed: Replace CAS references with EU Login.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1837: Replace CAS references with EU Login.

---

oe_authentication.module

Allow User 1 to delete user accounts in Drupal
- Added:
- Changed: Allow User 1 to delete user accounts in Drupal
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1750: Allow user 1 to delete users.

---

CHANGELOG.md

Create release 1.0.0-alpha6.
- Added:
- Changed: CHANGELOG.md
- Deprecated:
- Removed:
- Fixed:
- Security:

OPENEUROPA-1813: Create release 1.0.0-alpha6.

---

CHANGELOG.md

Create release 1.0.0-alpha7.
- Added:
- Changed: CHANGELOG.
- Deprecated:
- Removed:
- Fixed:
- Security:

OPENEUROPA-1813: Create release 1.0.0-alpha7.

---

.drone.yml
composer.json
docker-compose.yml
tests/Behat/AuthenticationContext.php

Use PHP 7.2 in drone and docker image.
- Added: PHP 7.2 usage in docker-compose and drone.
- Fixed: Remove unused `use` statement from `tests/Behat/AuthenticationContext.php`.

OPENEUROPA-2258: Use PHP 7.2 in drone and docker image.

---

modules/oe_authentication_user_fields/oe_authentication_user_fields.info.yml
modules/oe_authentication_user_fields/oe_authentication_user_fields.module
modules/oe_authentication_user_fields/oe_authentication_user_fields.services.yml
modules/oe_authentication_user_fields/src/EuLoginAttributesHelper.php
modules/oe_authentication_user_fields/src/EventSubscriber/EuLoginAttributesToUserFieldsSubscriber.php
oe_authentication.install
oe_authentication.module
oe_authentication.post_update.php
runner.yml.dist
src/CasProcessor.php
src/Event/EuLoginEventSubscriber.php
tests/features/ecas-login.feature

Fixes #81
Is covered by the Behat tests.
Install de development environment according to the README.md.
```bash
git checkout master
./vendor/bin/run drupal:site-setup
./vendor/bin/run drupal:site-install
./vendor/bin/drush -l http://localhost/path/to/site/ uli
```
Go to `/admin/reports/status` and check that there are no Entity/Field Definitions mismatch errors.
Do a login for a test user (see the eCAS Mock Server users data) and, in the `users_field_data` table, check that the profile fields (`field_oe_*`) are correctly filled.
```bash
git checkout 81-user-fields
./vendor/bin/drush updb -y
```
Refresh `/admin/reports/status` and check that there are no Entity/Field Definitions mismatch errors.
Check the `users_field_data` table. The fields should be filled with the previous data.

Move user fields into a sub-module

---

composer.json

Fix the drupal/cas version to 1.6.
- Added:
- Changed: Fix the drupal/cas version to 1.6.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-0000: Fix the drupal/cas version to 1.6.

---

CHANGELOG.md

Prepare 1.3.0 release.
- Added:
- Changed: Update changelog for 1.3.0.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare 1.3.0 release.

---

behat.yml.dist
composer.json
src/CasProcessor.php
src/Event/EuLoginEventSubscriber.php
src/Event/MessengerEuLoginEventSubscriber.php
tests/Behat/AuthenticationContext.php
tests/features/ecas-login.feature
tests/features/ecas-register.feature

Not allow to register a user from CAS if a user with the same email exists locally. Inform of this error with a friendly message.
- Added: 
- Changed: Modifications to an already subscribed events
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OEL-153: Prevent CAS from creating a new user account if the email is already taken.

---

modules/oe_authentication_user_fields/oe_authentication_user_fields.services.yml
modules/oe_authentication_user_fields/src/Commands/sql/UserSanitizeCommand.php
modules/oe_authentication_user_fields/tests/src/Functional/UserSanitizeCommandTest.php

On one of the sites (Epale – from EACEA) the sanitization led to memory issues and following further investigation the problem was pinpointed to the new sanitization in oe_authentication (see https://github.com/openeuropa/oe_authentication/commit/e3ca1f5527c10363db010b39d8950b778aab89cb). The problem is that the code implemented is loading in memory all users in a single go as objects and therefore the memory needed depends linearly on the number of users. For a large site such as EPALE (~130K users) this leads to more than 5GB RAM needed for the sanitization. Furthermore, the sanitization is done one by one which requires a very long time.
Related Github issue: https://github.com/openeuropa/oe_authentication/issues/152
- Added:
- Changed: …

EWPP-2210: Optimize query for sanitizing of user data.

---

CHANGELOG.md
config/schema/oe_authentication.schema.yml
src/Form/AuthenticationSettingsForm.php
tests/Functional/SettingsFormTest.php
tests/modules/oe_authentication_test/config/schema/oe_authentication_test.schema.yml
tests/modules/oe_authentication_test/oe_authentication_test.info.yml
tests/modules/oe_authentication_test/src/Plugin/Condition/UserTestCondition.php

OPES-1546: Allow to configure user conditions for 2FA

---

modules/oe_authentication_corporate_roles/tests/src/Kernel/CorporateRolesTest.php
oe_authentication.services.yml
runner.yml.dist
src/Event/TwoFactorAuthenticationEventSubscriber.php
src/Form/AuthenticationSettingsForm.php
tests/Functional/SettingsFormTest.php
tests/Functional/TwoFactorAuthenticationTest.php
tests/Kernel/EuLoginEventSubscriberTest.php
tests/modules/oe_authentication_test/config/schema/oe_authentication_test.schema.yml
tests/modules/oe_authentication_test/src/Plugin/Condition/UserTestCondition.php

Fixes #204 .
Logic implemented in this PR (pseudocode):
```
if (force_2fa)
force 2fa for all users, by sending the parameters to eulogin
elseif (no conditions enabled)
don't force 2fa for any user
elseif (no conditions match for user)
don't force 2fa for this user
else
Require 2fa:
Reject login attempt for this user, if 2fa was not used.
User needs to actively choose a 2fa method in eulogin.
```

OPES-1547: Apply configured conditions on user login

---

modules/oe_authentication_user_fields/oe_authentication_user_fields.module

Fixes https://github.com/openeuropa/oe_authentication/issues/208
It seems that some sites load services that in their constructor end up calling in the stack trace a user load. And this causes the container to crash because the new user field doesn't exist (user__field_oe_ldap_groups). 
This is very difficult to reproduce, the only way I managed was to add to the constructor of a random service, a User::loadMultiple(). But not just any service. I tried with ExternalAuth where it was fine. But then in DatabaseLockBackend it crashed. I think it may happen only in cases in which the service in question is a dependency of another service.

EWPP-4910: Prevent crash on release update hooks.

---

config/install/oe_authentication.settings.yml
oe_authentication.post_update.php

See https://github.com/openeuropa/oe_authentication/issues/229

Issue #229: Missing "langcode" in oe_authentication.settings.
