.drone.yml
README.md
composer.json
docker-compose.yml

Update images on docker-compose and drone file.
- Changed: Images on docker-compose and drone file.
```sh
no commands
```

OPENEUROPA-582: Update images on docker-compose and drone file.

---

.drone.yml
tests/features/user-management.feature

OPENEUROPA-1533: Add --strict flag for Behat tests execution.

---

CHANGELOG.md

Prepare the release 1.0.0-alpha4.

OPENEUROPA-1520: Prepare for release 1.0.0-alpha4

---

composer.json
oe_authentication.install
tests/features/ecas-login.feature

Fix cas module version and solve config issue.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1657: Fix cas module version.

---

.drone.yml
README.md
composer.json
tests/features/configure_authentication.feature
tests/features/drupal-login.feature
tests/features/ecas-login.feature
tests/features/ecas-register.feature
tests/features/user-management.feature

Maintenance task to address issue #53.
- Changed: Improve README file.
- Changed: Drone to use lighter images.
- Removed: Twig dependency.
- Added: Patch "https://www.drupal.org/project/cas/issues/3047390": "https://www.drupal.org/files/issues/2019-04-12/3047390_2.patch"

OPENEUROPA-627

---

composer.json

OPENEUROPA-1766: Fix Drupal 8.7.

---

CHANGELOG.md

Create release 1.0.0-beta1
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1864: Create release 1.0.0-beta1.

---

.drone.yml

Separate cache folder on drone.

OPENEUROPA-0000: Separate cache folder on drone.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-0000: Preparing for 1.1.0 release.

---

.drone.yml
composer.json
docker-compose.yml

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-2939: PHP 7.3. - Update OE Authentication component.

---

CHANGELOG.md

Update changelog for release 1.5.0.
- Added:
- Changed: Update changelog for release 1.5.0.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.5.0.

---

CHANGELOG.md

Fix release 1.5.0 Changelog.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Fix release 1.5.0 Changelog.

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-1732: Replace patch for cas module.

---

CHANGELOG.md

Prepare release 1.5.1.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.5.1.

---

oe_authentication.install
oe_authentication.post_update.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-2133: Update default email hostname for eulogin user bulk import.

---

composer.json

OEL-1978: Unlock symfony/http-foundation

---

modules/oe_authentication_eulogin_mock/oe_authentication_eulogin_mock.services.yml
modules/oe_authentication_eulogin_mock/src/EventSubscriber/CasPreRedirectSubscriber.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-2946: Fix force login redirect which is caheable by varnish.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.13.0.

---

config/install/oe_authentication.settings.yml
config/schema/oe_authentication.schema.yml
oe_authentication.post_update.php
src/Event/TwoFactorAuthenticationEventSubscriber.php
src/Form/AuthenticationSettingsForm.php
tests/Functional/TwoFactorAuthenticationTest.php
tests/features/configure_authentication.feature
tests/modules/oe_authentication_test/oe_authentication_test.services.yml
tests/modules/oe_authentication_test/src/TestLoggerDecorator.php

OPES-1548: Allow developers to customise the message shown when a login is denied for missing 2FA

---

src/Event/EuLoginEventSubscriber.php
tests/Kernel/EuLoginEventSubscriberTest.php

OPES-1544: Replace authentication method outdated property.
